<a href="https://colab.research.google.com/github/skwhdeo/google-colab/blob/master/myPyTorchTest_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy
import matplotlib.pyplot as plt

x = torch.ones(3,2)
print(x)

x = torch.zeros(2,3)
print(x)

torch.manual_seed(2)
x = torch.rand(2,2)
print(x)


print(x)


tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6147, 0.3810],
        [0.6371, 0.4745]])
