<a href="https://colab.research.google.com/github/skwhdeo/google-colab/blob/master/myPyTorchTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy
import matplotlib.pyplot as plt

x = torch.ones(3,2)
print(x)

x = torch.zeros(2,3)
print(x)

torch.manual_seed(2)
x = torch.rand(2,2)
print(x)

x = x.new_ones(5, 3, dtype=torch.int)      # new_* 메소드는 크기를 받습니다
print(x)

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6147, 0.3810],
        [0.6371, 0.4745]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[-0.3195, -1.2050,  1.0445],
        [-0.6332,  0.5731,  0.5409],
        [-0.3919, -1.0427,  1.3186],
        [ 0.7476, -1.3265, -1.2413],
        [-0.1028, -0.9498,  0.6181]])
