<a href="https://colab.research.google.com/github/skwhdeo/google-colab/blob/master/myPyTorchTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import torch
import numpy
import matplotlib.pyplot as plt

x = torch.ones(2,3)
print(x)

a = torch.zeros(2,3)
print(a)

torch.manual_seed(2)
b = torch.rand(2,3)
print(b)
print(b.size())
print(b.size()[1])
print(x+b)

print(x.add_(b))


print(x[:,0:2])


a = torch.zeros(4,4)
aa = a.view(-1,2)
print(aa.size())
print(aa)
print(aa.add_(100))
print(aa.mul_(0.1))


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6147, 0.3810, 0.6371],
        [0.4745, 0.7136, 0.6190]])
torch.Size([2, 3])
3
tensor([[1.6147, 1.3810, 1.6371],
        [1.4745, 1.7136, 1.6190]])
tensor([[1.6147, 1.3810, 1.6371],
        [1.4745, 1.7136, 1.6190]])
tensor([[1.6147, 1.3810],
        [1.4745, 1.7136]])
torch.Size([8, 2])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.],
        [100., 100.]])
tensor([[10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.],
        [10., 10.]])
